/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Meta
         * @description Constants, the indicator catalogue, and launch defaults.
         */
        get: operations["get_meta_api_v1_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Health
         * @description Whether the database is reachable and its schema is the one this build expects.
         *
         *     503 when it is not, so a probe fails on the condition rather than on the first request that
         *     happens to touch a missing table. The body still describes what is wrong -- an unhealthy
         *     answer that says only "unhealthy" sends the reader to the logs for something the check
         *     already knows.
         */
        get: operations["get_health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate Config
         * @description Check a configuration without storing or running anything.
         *
         *     Always 200: a config the user is halfway through typing is what this exists for, and
         *     invalidity is the answer rather than a transport failure.
         */
        post: operations["validate_config_api_v1_config_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Diff Configs
         * @description Compare two configurations, neither of which need be a stored version.
         *
         *     The Promote dialog's diff. ``GET /strategies/{id}/diff`` cannot serve it: that compares two
         *     versions of one strategy, and the configuration a search produced is not a version of
         *     anything until the user adopts it. Invalid input is a 4xx here rather than the 200 that
         *     ``/config/validate`` returns -- there is no half-typed state to support, and a diff against
         *     a configuration that is not a strategy has nothing to say.
         */
        post: operations["diff_configs_api_v1_config_diff_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strategies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Strategies
         * @description The list screen. ``search`` matches name or ticker; ``verdict`` is the filter chips.
         */
        get: operations["list_strategies_api_v1_strategies_get"];
        put?: never;
        /**
         * Post Strategy
         * @description Create a strategy and its v1. No run is launched; it starts never-run.
         */
        post: operations["post_strategy_api_v1_strategies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strategies/{strategy_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Strategy
         * @description The detail header and the head configuration.
         */
        get: operations["get_strategy_api_v1_strategies__strategy_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete One Strategy
         * @description Delete a strategy, its versions, its runs and their captured series. **Irreversible.**
         *
         *     The only endpoint in the interface that destroys anything, and the only exception to the
         *     no-delete guarantee of spec section 15.2 -- narrowed, not withdrawn: versions and runs
         *     remain undeletable in their own right, and no endpoint removes one without its strategy.
         *
         *     ``409`` when a run is still queued or running, or when a fork or promotion descends from
         *     it; the detail names what is in the way. ``200`` carries a receipt of what went, because
         *     an irreversible operation that answers with an empty body leaves the caller to guess how
         *     much it did.
         */
        delete: operations["delete_one_strategy_api_v1_strategies__strategy_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strategies/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Import
         * @description Import a configuration file, stored exactly as written.
         *
         *     Warnings ride along on the success: they never block, so an import with a shadowed stop
         *     still produces the strategy the file describes.
         */
        post: operations["post_import_api_v1_strategies_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strategies/{strategy_id}/fork": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Fork
         * @description Copy a strategy at some version into a new one starting at v1.
         */
        post: operations["post_fork_api_v1_strategies__strategy_id__fork_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strategies/{strategy_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Versions
         * @description The history timeline, newest first.
         *
         *     Each entry's change summary is computed against its predecessor at read time. Storing it
         *     would let a summary drift from the configs it claims to describe.
         */
        get: operations["list_versions_api_v1_strategies__strategy_id__versions_get"];
        put?: never;
        /**
         * Create Version
         * @description Save an edit as the next version.
         *
         *     Refused with 409 if the head moved under the edit, and refused if nothing changed.
         */
        post: operations["create_version_api_v1_strategies__strategy_id__versions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strategies/{strategy_id}/versions/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Version
         * @description One immutable version, exactly as it was saved.
         */
        get: operations["get_version_api_v1_strategies__strategy_id__versions__version__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strategies/{strategy_id}/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Diff Versions
         * @description Compare two versions, grouped by config section.
         */
        get: operations["diff_versions_api_v1_strategies__strategy_id__diff_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strategies/{strategy_id}/versions/{version}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore
         * @description Append a copy of an older version at the head. Nothing is rewound.
         */
        post: operations["restore_api_v1_strategies__strategy_id__versions__version__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strategies/{strategy_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Run
         * @description Queue a run. 202: it is accepted, not finished.
         *
         *     The caller returns to the strategy immediately and watches progress over ``/events``; the
         *     worker picks the run up from the queue.
         */
        post: operations["post_run_api_v1_strategies__strategy_id__runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Runs
         * @description The run tabs, the all-runs page, the queue, and the chart picker.
         */
        get: operations["get_runs_api_v1_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run
         * @description One run: the engine's serialised result verbatim, its checks, and what it changed.
         */
        get: operations["get_run_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/promote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Promote
         * @description Turn a run's winning configuration into a strategy of its own.
         *
         *     One transaction: the strategy, its v1, and a backtest already queued against it -- so the
         *     promoted strategy is never sitting there with no numbers at all, inviting the reader to
         *     supply them from memory of a run that measured a different config.
         *
         *     409 if the run is a backtest (nothing to promote), has not succeeded, or the name is taken.
         */
        post: operations["post_promote_api_v1_runs__run_id__promote_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Cancel
         * @description Ask a run to stop. A queued run ends at once; a running one at its next checkpoint.
         */
        post: operations["post_cancel_api_v1_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Series Catalog
         * @description Which series this run captured. Fold 0 is the whole run.
         */
        get: operations["get_series_catalog_api_v1_runs__run_id__series_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/series/{name}.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Series Csv
         * @description The same series as CSV, streamed from the same stored points.
         *
         *     The chart and the file are therefore the same bytes: an export that recomputed anything
         *     could disagree with the picture it claims to be.
         */
        get: operations["get_series_csv_api_v1_runs__run_id__series__name__csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/series/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Series
         * @description One captured series, exactly as it was stored at run time.
         */
        get: operations["get_series_api_v1_runs__run_id__series__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Events
         * @description Live run updates. Payloads carry no result; clients refetch the run.
         */
        get: operations["stream_events_api_v1_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ChangeOut
         * @description One leaf that differs between two configurations.
         */
        ChangeOut: {
            /** Path */
            path: string;
            /** Old */
            old?: unknown;
            /** New */
            new?: unknown;
        };
        /**
         * CheckOut
         * @description One robustness check, exactly as the engine reported it.
         */
        CheckOut: {
            /** Name */
            name: string;
            /** Label */
            label: string;
            /** Passed */
            passed: boolean;
            /** Plain */
            plain: string;
            /** Stat */
            stat: string;
            /** Detail */
            detail: string;
        };
        /**
         * ConfigDiffRequest
         * @description Two configurations to compare, each in either form.
         *
         *     Deliberately not addressed by version. The version-to-version diff answers "what did I
         *     change"; this answers "what am I about to adopt", where one side is a configuration a
         *     search produced and has no version at all until the user promotes it.
         */
        ConfigDiffRequest: {
            from: components["schemas"]["ValidateRequest"];
            to: components["schemas"]["ValidateRequest"];
        };
        /**
         * ConfigDiffResponse
         * @description Two configurations compared. No version refs: one side may not be a version at all.
         */
        ConfigDiffResponse: {
            /** Groups */
            groups: components["schemas"]["SectionDiffOut"][];
            /** From Yaml */
            from_yaml: string;
            /** To Yaml */
            to_yaml: string;
        };
        /**
         * CreateStrategyRequest
         * @description The New-strategy dialog.
         */
        CreateStrategyRequest: {
            /** Name */
            name: string;
            /** Ticker */
            ticker: string;
            /** Start Date */
            start_date: string;
            /** End Date */
            end_date: string;
            /**
             * Interval
             * @default 1d
             */
            interval: string;
            /**
             * Seed
             * @default minimal
             */
            seed: string;
        };
        /**
         * CreatedStrategy
         * @description What a create, import or fork produced.
         */
        CreatedStrategy: {
            strategy: components["schemas"]["StrategyDetail"];
            /**
             * Warnings
             * @default []
             */
            warnings: components["schemas"]["Issue"][];
        };
        /**
         * DeletedStrategy
         * @description What a delete destroyed.
         *
         *     A body rather than a bare 204. The operation is irreversible and the interface should be
         *     able to say how much it removed -- "deleted Momentum: 4 versions, 11 runs" is a receipt,
         *     and a user who expected one run and reads eleven has learned something while it still
         *     matters that they know it.
         */
        DeletedStrategy: {
            /** Name */
            name: string;
            /** Versions */
            versions: number;
            /** Runs */
            runs: number;
            /** Series */
            series: number;
        };
        /**
         * DiffResponse
         * @description Two versions compared, grouped for reading and with both YAML panes.
         */
        DiffResponse: {
            from_version: components["schemas"]["VersionSummaryRef"];
            to_version: components["schemas"]["VersionSummaryRef"];
            /** Groups */
            groups: components["schemas"]["SectionDiffOut"][];
            /** From Yaml */
            from_yaml: string;
            /** To Yaml */
            to_yaml: string;
        };
        /**
         * ForkStrategyRequest
         * @description Copy an existing strategy at some version. ``version`` defaults to the head.
         */
        ForkStrategyRequest: {
            /** Name */
            name: string;
            /** Version */
            version?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description What the process can honestly say about itself.
         */
        HealthResponse: {
            /** Ok */
            ok: boolean;
            /** Database */
            database: boolean;
            /** Migrations Current */
            migrations_current: boolean;
            /** Applied Migrations */
            applied_migrations: number;
            /** Pending Migrations */
            pending_migrations: string[];
            /** Migration Refusal */
            migration_refusal: string | null;
            /** Version */
            version: string;
        };
        /**
         * ImportStrategyRequest
         * @description An uploaded configuration file, stored as written.
         */
        ImportStrategyRequest: {
            /** Yaml */
            yaml: string;
            /** Filename */
            filename?: string | null;
        };
        /**
         * Issue
         * @description One validation problem, addressed to the field that caused it.
         */
        Issue: {
            /** Path */
            path: string;
            /** Message */
            message: string;
            /** Line */
            line?: number | null;
            /** Suggestion */
            suggestion?: string | null;
        };
        /**
         * LaunchRunRequest
         * @description Launch a run against the strategy's head.
         *
         *     No version field: a client cannot ask to run an old config. The head at launch time is
         *     pinned by the server, which is the only answer that stays true about what produced the
         *     numbers.
         */
        LaunchRunRequest: {
            /** Kind */
            kind: string;
            /** Params */
            params?: {
                [key: string]: unknown;
            };
            /** Seed */
            seed?: number | null;
        };
        /**
         * Lineage
         * @description Where a strategy came from.
         */
        Lineage: {
            /** Origin */
            origin: string;
            /** Parent Strategy Id */
            parent_strategy_id?: string | null;
            /** Parent Version */
            parent_version?: number | null;
            /** Origin Run Id */
            origin_run_id?: string | null;
        };
        /**
         * MetaResponse
         * @description Static engine facts. Serialised from the engine's own constants, never restated.
         */
        MetaResponse: {
            /** Engine Version */
            engine_version: string;
            /** Trade Floor */
            trade_floor: number;
            /** Significance */
            significance: number;
            /** Instability Threshold */
            instability_threshold: number;
            /** Objectives */
            objectives: string[];
            /** Fold Schemes */
            fold_schemes: string[];
            /** Defaults */
            defaults: {
                [key: string]: unknown;
            };
            /** Evolution Warmup Bars */
            evolution_warmup_bars: number;
            /** Indicators */
            indicators: {
                [key: string]: unknown;
            }[];
            /** Exit Fields */
            exit_fields: {
                [key: string]: unknown;
            }[];
            /** Intervals */
            intervals: {
                [key: string]: unknown;
            }[];
            /** Limits */
            limits: string[];
        };
        /**
         * ParameterMoveOut
         * @description One parameter the winning config moved, against the run's own base version.
         */
        ParameterMoveOut: {
            /** Path */
            path: string;
            /** Old */
            old?: unknown;
            /** New */
            new?: unknown;
            /** Low */
            low?: number | null;
            /** High */
            high?: number | null;
            /**
             * At Bound
             * @default false
             */
            at_bound: boolean;
        };
        /**
         * PromoteRequest
         * @description The promote dialog. ``name`` defaults to the server's suggestion.
         */
        PromoteRequest: {
            /** Name */
            name?: string | null;
        };
        /**
         * PromotedStrategy
         * @description What a promotion produced.
         *
         *     ``carried_warning`` is not decoration: it says the new strategy starts flagged, and the
         *     client is expected to show that rather than present a fresh-looking strategy whose numbers
         *     came from an unvalidated search.
         */
        PromotedStrategy: {
            /**
             * Strategy Id
             * Format: uuid
             */
            strategy_id: string;
            version: components["schemas"]["VersionOut"];
            /**
             * Backtest Run Id
             * Format: uuid
             */
            backtest_run_id: string;
            /** Carried Warning */
            carried_warning: boolean;
        };
        /**
         * PromotedWarningOut
         * @description Shown until a promoted strategy's own walk-forward passes.
         */
        PromotedWarningOut: {
            /**
             * Origin Run Id
             * Format: uuid
             */
            origin_run_id: string;
            /** Origin Run Number */
            origin_run_number: number;
            /** Parent Name */
            parent_name: string | null;
            /** Text */
            text: string;
        };
        /**
         * RestoreVersionRequest
         * @description Append a copy of an older version at the head.
         */
        RestoreVersionRequest: {
            /** Note */
            note?: string | null;
        };
        /**
         * RunDetail
         * @description One run, with the engine's own serialised result passed through untouched.
         *
         *     ``result`` is exactly what ``cracktrade.serialize.to_dict`` produced, contractual derived
         *     properties included (spec section 15.1). Nothing here reshapes it, and nothing recomputes a
         *     verdict from it: ``checks`` is the engine's own list, read out of that same result.
         */
        RunDetail: {
            run: components["schemas"]["RunOut"];
            /** Result */
            result: {
                [key: string]: unknown;
            } | null;
            /** Error */
            error: {
                [key: string]: unknown;
            } | null;
            /** Checks */
            checks: components["schemas"]["CheckOut"][];
            /** Config Diff */
            config_diff: components["schemas"]["ParameterMoveOut"][];
            /** Default Promote Name */
            default_promote_name: string | null;
        };
        /**
         * RunList
         * @description A page of runs.
         */
        RunList: {
            /** Runs */
            runs: components["schemas"]["RunOut"][];
            /** Total */
            total: number;
        };
        /**
         * RunOut
         * @description A run as every list and header renders it.
         */
        RunOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Number */
            number: number;
            /** Kind */
            kind: string;
            /** Status */
            status: string;
            /** Strategy */
            strategy: {
                [key: string]: unknown;
            };
            /** Version */
            version: number;
            /** Interval */
            interval: string;
            /** Stale */
            stale: boolean;
            /** Params */
            params: {
                [key: string]: unknown;
            };
            /** Seed */
            seed: number;
            /**
             * Queued At
             * Format: date-time
             */
            queued_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Elapsed Seconds */
            elapsed_seconds: number | null;
            /** Progress */
            progress: {
                [key: string]: unknown;
            } | null;
            /** Failure Category */
            failure_category: string | null;
            /** Headline */
            headline: {
                [key: string]: unknown;
            } | null;
            /** Promotable */
            promotable: boolean;
            /** Cancel Requested */
            cancel_requested: boolean;
        };
        /**
         * SaveVersionRequest
         * @description An edit from the config editor.
         *
         *     ``base_version`` is what makes the save optimistic: it states which version the edit was
         *     made against, so a head that moved underneath is a conflict rather than a silent overwrite.
         */
        SaveVersionRequest: {
            /** Base Version */
            base_version: number;
            /** Config */
            config?: {
                [key: string]: unknown;
            } | null;
            /** Yaml */
            yaml?: string | null;
            /** Note */
            note?: string | null;
        };
        /**
         * SavedVersion
         * @description A newly appended version, and how many runs it just made stale.
         */
        SavedVersion: {
            version: components["schemas"]["VersionOut"];
            /** Stale Runs */
            stale_runs: number;
        };
        /**
         * SearchableParameterOut
         * @description A parameter an optimization would move, and its bounds.
         */
        SearchableParameterOut: {
            /** Path */
            path: string;
            /** Value */
            value: number;
            /** Low */
            low: number;
            /** High */
            high: number;
        };
        /**
         * SectionDiffOut
         * @description What changed in one config section, and what that means.
         */
        SectionDiffOut: {
            /** Section */
            section: string;
            /** Changes */
            changes: components["schemas"]["ChangeOut"][];
            /** Consequence */
            consequence: string | null;
        };
        /**
         * SeriesCatalog
         * @description Which chart series a run captured, and for which folds.
         */
        SeriesCatalog: {
            /** Series */
            series: {
                [key: string]: number[];
            };
        };
        /**
         * SeriesPoints
         * @description One captured series, exactly as stored.
         */
        SeriesPoints: {
            /** Name */
            name: string;
            /** Fold */
            fold: number;
            /** Points */
            points: {
                [key: string]: unknown;
            };
        };
        /**
         * StrategyDetail
         * @description The detail header plus the head configuration.
         */
        StrategyDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            lineage: components["schemas"]["Lineage"];
            /** Origin Not Credible */
            origin_not_credible: boolean;
            head: components["schemas"]["VersionOut"];
            /** Counts */
            counts: {
                [key: string]: number;
            };
            verdict: components["schemas"]["VerdictBlockOut"];
            /** Verdict Run Id */
            verdict_run_id: string | null;
            promoted_warning: components["schemas"]["PromotedWarningOut"] | null;
        };
        /**
         * StrategyList
         * @description The list screen, with the totals its filter chips show.
         */
        StrategyList: {
            /** Strategies */
            strategies: components["schemas"]["StrategySummary"][];
            /** Totals */
            totals: {
                [key: string]: number;
            };
        };
        /**
         * StrategySummary
         * @description A row of the strategy list, verdict included.
         */
        StrategySummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Ticker */
            ticker: string | null;
            /** Start Date */
            start_date: string | null;
            /** End Date */
            end_date: string | null;
            /** Interval */
            interval: string;
            /** Head Version */
            head_version: number;
            /**
             * Edited At
             * Format: date-time
             */
            edited_at: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            lineage: components["schemas"]["Lineage"];
            /** Origin Not Credible */
            origin_not_credible: boolean;
            /** Verdict */
            verdict: string;
            /** Verdict Run Id */
            verdict_run_id: string | null;
            /** Optimize Runs */
            optimize_runs: number;
            /** Backtest Runs */
            backtest_runs: number;
            /** Walk Forward Runs */
            walk_forward_runs: number;
            /** Evolve Runs */
            evolve_runs: number;
            /** Versions */
            versions: number;
            /** Last Run Id */
            last_run_id: string | null;
            /** Last Run Kind */
            last_run_kind: string | null;
            /** Last Run Status */
            last_run_status: string | null;
            /** Last Run At */
            last_run_at: string | null;
        };
        /**
         * ValidateRequest
         * @description A configuration to check, in either form. Exactly one must be supplied.
         */
        ValidateRequest: {
            /** Config */
            config?: {
                [key: string]: unknown;
            } | null;
            /** Yaml */
            yaml?: string | null;
        };
        /**
         * ValidateResponse
         * @description The editor's answer. ``valid: false`` arrives with 200 -- invalidity is the answer.
         */
        ValidateResponse: {
            /** Valid */
            valid: boolean;
            /** Errors */
            errors: components["schemas"]["Issue"][];
            /** Warnings */
            warnings: components["schemas"]["Issue"][];
            /** Canonical Yaml */
            canonical_yaml: string | null;
            /** Config */
            config: {
                [key: string]: unknown;
            } | null;
            /** Namespace */
            namespace: string[];
            /** Searchable Parameters */
            searchable_parameters: components["schemas"]["SearchableParameterOut"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VerdictBlockOut
         * @description The verdict banner: the state, the run that produced it, and what failed.
         *
         *     ``failures`` is the engine's own list and is present whenever the verdict is
         *     ``not_credible``. A client rendering the state without it would show a red badge with no
         *     reason, which is the fastest way to teach someone to ignore the badge.
         */
        VerdictBlockOut: {
            /** State */
            state: string;
            /** Run Id */
            run_id?: string | null;
            /** Run Number */
            run_number?: number | null;
            /** Version */
            version?: number | null;
            /** Finished At */
            finished_at?: string | null;
            /** Summary */
            summary?: string | null;
            /**
             * Failures
             * @default []
             */
            failures: string[];
            /**
             * Checks
             * @default []
             */
            checks: components["schemas"]["VerdictCheck"][];
            /** Meta */
            meta?: string | null;
        };
        /**
         * VerdictCheck
         * @description One robustness check behind the verdict, as the engine reported it.
         */
        VerdictCheck: {
            /** Name */
            name: string;
            /** Label */
            label: string;
            /** Passed */
            passed: boolean;
            /** Plain */
            plain: string;
            /** Stat */
            stat: string;
            /** Detail */
            detail: string;
        };
        /**
         * VersionOut
         * @description One immutable version.
         */
        VersionOut: {
            /** Version */
            version: number;
            /** Origin */
            origin: string;
            /** Restored From */
            restored_from: number | null;
            /** Note */
            note: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Config */
            config: {
                [key: string]: unknown;
            };
            /** Yaml */
            yaml: string;
        };
        /**
         * VersionSummary
         * @description A history-timeline entry: what changed, and what it means for earlier runs.
         */
        VersionSummary: {
            /** Version */
            version: number;
            /** Head */
            head: boolean;
            /** Origin */
            origin: string;
            /** Restored From */
            restored_from: number | null;
            /** Note */
            note: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Change Summary */
            change_summary: components["schemas"]["ChangeOut"][];
            /** Flags */
            flags: string[];
            /** Runs Against */
            runs_against: number;
        };
        /**
         * VersionSummaryRef
         * @description Enough of a version to label a diff pane.
         */
        VersionSummaryRef: {
            /** Version */
            version: number;
            /** Origin */
            origin: string;
            /** Restored From */
            restored_from: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Head */
            head: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_meta_api_v1_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaResponse"];
                };
            };
        };
    };
    get_health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    validate_config_api_v1_config_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    diff_configs_api_v1_config_diff_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigDiffRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigDiffResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_strategies_api_v1_strategies_get: {
        parameters: {
            query?: {
                search?: string | null;
                verdict?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_strategy_api_v1_strategies_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStrategyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedStrategy"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_strategy_api_v1_strategies__strategy_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_one_strategy_api_v1_strategies__strategy_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeletedStrategy"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_import_api_v1_strategies_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportStrategyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedStrategy"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_fork_api_v1_strategies__strategy_id__fork_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForkStrategyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedStrategy"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_versions_api_v1_strategies__strategy_id__versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_version_api_v1_strategies__strategy_id__versions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveVersionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedVersion"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_version_api_v1_strategies__strategy_id__versions__version__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: string;
                version: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    diff_versions_api_v1_strategies__strategy_id__diff_get: {
        parameters: {
            query: {
                from: number;
                to: number;
            };
            header?: never;
            path: {
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiffResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_api_v1_strategies__strategy_id__versions__version__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: string;
                version: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RestoreVersionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_run_api_v1_strategies__strategy_id__runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LaunchRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_runs_api_v1_runs_get: {
        parameters: {
            query?: {
                strategy_id?: string | null;
                kind?: string | null;
                status?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_promote_api_v1_runs__run_id__promote_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromoteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromotedStrategy"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_cancel_api_v1_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_series_catalog_api_v1_runs__run_id__series_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesCatalog"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_series_csv_api_v1_runs__run_id__series__name__csv_get: {
        parameters: {
            query?: {
                fold?: number;
            };
            header?: never;
            path: {
                run_id: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_series_api_v1_runs__run_id__series__name__get: {
        parameters: {
            query?: {
                fold?: number;
            };
            header?: never;
            path: {
                run_id: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesPoints"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_events_api_v1_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
